### PR TITLE
Fixed error

### PR DESCRIPTION
**Pull request by Qwerty-Space**
`'error loading module 'cjson' from file 'usr/local/lib/lua/5.2/cjson.so'`

#298

### CODE REVIEW

**Comment by NotAFile** [comment]
I'd rather this was fixed upstream, but I guess this is a good workaround for now.

**Comment by Qwerty-Space** [comment]
The issue is with lua-cjson I think.  I found that another project had a similar issue with installing lua-cjson with luarocks on the latest version at the time.

**Comment by NotAFile** [comment]
yes, this has been reported in the lua-cjson repository

**Comment by NotAFile** [comment]
lua cjson appears to have made changes that break the library under lua5.2 and 5.3

**Comment by webr0m** [comment]
to fix this downgrade past version c-json 2.1.0-1 

`sudo luarocks install https://luarocks.org/manifests/openresty/lua-cjson-2.1.0-1.rockspec`

**Comment by yangm97** [comment]
I’m going to close this since the official lua version of the project is no lua 5.1.

**Pull request closed without merging**
