### PR TITLE
Fix old update skipped

### PR DESCRIPTION
**Pull request by riskey95**
This my result `timedatectl`

This my config.lua

I try to make custom command to see the result of `os.time(os.date('!*t'))` and compare with result of `msg.date`

### CODE REVIEW

**Comment by Qwerty-Space** [comment]
@riskey95 This raises the point that the /ping command should have a timestamp

**Comment by NotAFile** [comment]
Lua is indeed behaving weirdly. But assuming Localtime and UTC are the same is not a good solution, IMO.

**Comment by yangm97** [comment]
This would only *fix* some edge cases but by the wrong reasons (i.e. when lua adds the UTC time shift twice). Looking into using luatz instead of os.time.

**Comment by riskey95** [comment]
actually when use os.time(os.date('*t')) it will return to time in UTC time not local time
and i just change Old update skipped log to 'local time' because all log use local time when loging.

**Comment by NotAFile** [comment]
@riskey95 > actually when use os.time(os.date('*t')) it will return to time in UTC time not local time

Wow, that's weird. I can reproduce that. That's not documented anywhere either. I'm confused why it worked before.

**Comment by riskey95** [comment]
@NotAFile 
capture

**Comment by NotAFile** [comment]
the bot is running in UTC, right?

**Comment by riskey95** [comment]
yup.. you'll face this problem if your bot server local timezone is not set in UTC if you use `os.time(os.date("!*t")`

**Comment by NotAFile** [comment]
either way, this seems to work. I disagree with the change of the logging to local time though, because it makes the two times not comparable.

**Comment by riskey95** [comment]
It still comparable. and it esier to read because normal log is on local time format not utc format https://github.com/group-butler/GroupButler/blob/872ee15e07847b06b73487d6088c463999f02698/lua/main.lua#L107
screenshot_20180715-193631

**Pull request merged**
