### PR TITLE
fix $stats command & remove markdown

### PR DESCRIPTION
**Pull request by riskey95**
Signed-off-by: Rhiski Aprilianto <mail@rhiskiapril.com>

### CODE REVIEW

**Comment by Qwerty-Space** [comment]
What's wrong with the markdown?

**Comment by yangm97** [comment]
@Qwerty-Space I set logs to be html + enclosed by code tags to prevent looping by bad formatting

**Comment by yangm97** [comment]
@yangm97 which made startup log look ugly with unparsed markdown

**Comment by Qwerty-Space** [comment]
@yangm97 Oh fair enough.

**Pull request merged**
